VPATH               +=  keyboards/gboards/
VPATH               +=  keyboards/gboards/g/
SRC                 +=  g/engine.c
MOUSEKEY_ENABLE     = no      # Mouse keys
RGBLIGHT_ENABLE     = no      # Enable WS2812 RGB underlight.
OLED_ENABLE         = no
OLED_DRIVER         = SSD1306
EXTRAKEY_ENABLE     = yes
LTO_ENABLE          = yes
QMK_SETTINGS        = no
COMBO_ENABLE        = yes
NKRO_ENABLE         = yes
STENO_ENABLE        = yes
