// Copyright 2024 Dane Lipscombe (@dlip)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1500U

#define FORCE_NKRO

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP1
#define SERIAL_USART_RX_PIN GP0
#define SERIAL_USART_PIN_SWAP

#define EE_HANDS

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define JOYSTICK_DEBUG
#define JOYSTICK_BUTTON_COUNT 32
#define ANALOG_JOYSTICK_X_AXIS_PIN GP27
#define ANALOG_JOYSTICK_Y_AXIS_PIN GP28
#define ANALOG_JOYSTICK_CLICK_PIN GP29
/*#define ANALOG_JOYSTICK_SPEED_REGULATOR 5*/
/*#define ANALOG_JOYSTICK_AUTO_AXIS*/
/*#define ANALOG_JOYSTICK_READ_INTERVAL 100*/
/*#define ANALOG_JOYSTICK_CUTOFF*/
#define ANALOG_JOYSTICK_X_AXIS_ORIGIN 501
#define ANALOG_JOYSTICK_X_AXIS_MIN 25
#define ANALOG_JOYSTICK_X_AXIS_MAX 938
#define ANALOG_JOYSTICK_Y_AXIS_ORIGIN 474
#define ANALOG_JOYSTICK_Y_AXIS_MIN 58
#define ANALOG_JOYSTICK_Y_AXIS_MAX 942
#define DIP_SWITCH_PINS { GP29 }

#define PMW33XX_CPI 800
#define SPI_DRIVER SPID0
#define SPI_SCK_PIN GP2
#define SPI_MOSI_PIN GP3
#define SPI_MISO_PIN GP4
#define PMW33XX_CS_PIN GP5
#define POINTING_DEVICE_INVERT_X
