// Copyright 2024 Dane Lipscombe (@dlip)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1500U

#define FORCE_NKRO

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP1
#define SERIAL_USART_RX_PIN GP0
#define SERIAL_USART_PIN_SWAP

#define EE_HANDS


#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_COMBINED
#define ANALOG_JOYSTICK_X_AXIS_PIN GP26
#define ANALOG_JOYSTICK_Y_AXIS_PIN GP27
#define ANALOG_JOYSTICK_CLICK_PIN GP28
#define ANALOG_JOYSTICK_AUTO_AXIS
/*#define ANALOG_JOYSTICK_AXIS_MIN 550*/
/*#define ANALOG_JOYSTICK_AXIS_MAX 805*/

#define DIP_SWITCH_PINS { GP28 }
