SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor
JOYSTICK_ENABLE = yes
# DIP_SWITCH_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
SPI_DRIVER_REQUIRED = yes

## Joystick + PMW33XX
# POINTING_DEVICE_DRIVER = analog_joystick
# POINTING_DEVICE_DRIVER = pmw3389
# ANALOG_DRIVER_REQUIRED = yes

## Cirque
POINTING_DEVICE_DRIVER = cirque_pinnacle_spi
