#define ONESHOT_TIMEOUT 500
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define QUICK_TAP_TERM_PER_KEY
#define COMBO_VARIABLE_LEN
#define COMBO_TERM 100
#define TAPPING_TERM 300
#define CHORDAL_HOLD
#define PERMISSIVE_HOLD


/*#define JOYSTICK_DEBUG*/
#define JOYSTICK_BUTTON_COUNT 32
#define ANALOG_JOYSTICK_X_AXIS_PIN GP27
#define ANALOG_JOYSTICK_Y_AXIS_PIN GP28
#define ANALOG_JOYSTICK_CLICK_PIN GP29
#define ANALOG_JOYSTICK_X_AXIS_ORIGIN 501
#define ANALOG_JOYSTICK_X_AXIS_MIN 25
#define ANALOG_JOYSTICK_X_AXIS_MAX 938
#define ANALOG_JOYSTICK_Y_AXIS_ORIGIN 474
#define ANALOG_JOYSTICK_Y_AXIS_MIN 58
#define ANALOG_JOYSTICK_Y_AXIS_MAX 942
#define ANALOG_JOYSTICK_READ_INTERVAL 50
