#define ONESHOT_TIMEOUT 500
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define QUICK_TAP_TERM_PER_KEY
#define COMBO_VARIABLE_LEN
#define COMBO_TERM 80
#define TAPPING_TERM 190
// #define FLOW_TAP_TERM 20
#define CHORDAL_HOLD
#define PERMISSIVE_HOLD
#define CIRQUE_PINNACLE_POSITION_MODE  CIRQUE_PINNACLE_ABSOLUTE_MODE
// #define CIRQUE_PINNACLE_REACHABLE_CALIBRATION
#ifdef UF2_SPLIT_LEFT
#define CIRQUE_PINNACLE_X_LOWER 132
#define CIRQUE_PINNACLE_X_UPPER 1840
#define CIRQUE_PINNACLE_Y_LOWER 79
#define CIRQUE_PINNACLE_Y_UPPER 1452
// #define CIRQUE_PINNACLE_TAP_ENABLE
// #define CIRQUE_PINNACLE_SECONDARY_TAP_ENABLE
// #define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#else
#define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
#endif
