// Copyright 2023 Dane Lipscombe (@dlip)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

#define FORCE_NKRO

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP1
#define SERIAL_USART_RX_PIN GP0
#define SERIAL_USART_PIN_SWAP

#define EE_HANDS

// #define SPLIT_POINTING_ENABLE
// #define POINTING_DEVICE_COMBINED
// #define POINTING_DEVICE_RIGHT
#define PMW33XX_CPI 500

#define SPI_DRIVER SPID0
#define SPI_SCK_PIN GP2
#define SPI_MOSI_PIN GP3
#define SPI_MISO_PIN GP4
#define PMW33XX_CS_PIN GP5
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_DEBUG
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
