// Copyright 2023 Dane Lipscombe (@dlip)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

#undef NO_ACTION_ONESHOT

#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 1000

#define COMBO_TERM 50
#define COMBO_MUST_HOLD_MODS

#define TAP_CODE_DELAY 25
#define TAPPING_FORCE_HOLD