#define ONESHOT_TIMEOUT 500
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define QUICK_TAP_TERM_PER_KEY
#define COMBO_VARIABLE_LEN
#define COMBO_TERM 100
#define TAPPING_TERM 300
#define ACHORDION_STREAK
#define PERMISSIVE_HOLD
