#define JA_KA KC_T // カ
#define JA_KI KC_G // キ
#define JA_KU KC_H // ク
#define JA_KE KC_QUOT // ケ
#define JA_KO KC_B // コ
#define JA_SA KC_X // サ
#define JA_SHI KC_D // シ
#define JA_SU KC_R // ス
#define JA_SE KC_P // セ
#define JA_SO KC_C // ソ
#define JA_TA KC_Q // タ
#define JA_CHI KC_A // チ
#define JA_TSU KC_Z // ツ
#define JA_TE KC_W // テ
#define JA_TO KC_S // ト
#define JA_HA KC_F // ハ
#define JA_HI KC_V // ヒ
#define JA_FU KC_2 // フ
#define JA_HE KC_EQUAL // ヘ
#define JA_HO KC_MINUS // ホ
#define JA_YA KC_7 // ヤ
#define JA_YU KC_8 // ユ
#define JA_YO KC_9 // ヨ
#define JA_A KC_3 // ア
#define JA_I KC_E // イ
#define JA_U KC_4 // ウ
#define JA_E KC_5 // エ
#define JA_O KC_6 // オ
#define JA_RA KC_O // ラ
#define JA_RI KC_L // リ
#define JA_RU KC_DOT // ル
#define JA_RE KC_SCLN // レ
#define JA_RO KC_GRV // ロ
#define JA_MA KC_J // マ
#define JA_MI KC_N // ミ
#define JA_MU KC_BSLS // ム
#define JA_ME KC_SLSH // メ
#define JA_MO KC_M // モ
#define JA_NA KC_U // ナ
#define JA_NI KC_I // ニ
#define JA_NU KC_1 // ヌ
#define JA_NE KC_COMMA // ネ
#define JA_NO KC_K // ノ
#define JA_WA KC_0 // ワ
#define JA_WO KC_RPRN // ヲ
#define JA_N KC_Y // ン
#define JA_SEN KC_UNDS // ー
#define JA_DOT KC_GT // 。
#define JA_COM KC_LT // 、
#define JA_LQU KC_RCBR // 「
#define JA_RQU KC_PIPE // 」
#define JA_SLS KC_QUES // ・
#define JA_TEN KC_LBRC // ゛
#define JA_MAR KC_RBRC  // ゜


