#define JK_KA KC_T // カ
#define JK_KI KC_G // キ
#define JK_KU KC_H // ク
#define JK_KE KC_QUOT // ケ
#define JK_KO KC_B // コ
#define JK_SA KC_X // サ
#define JK_SHI KC_D // シ
#define JK_SU KC_R // ス
#define JK_SE KC_P // セ
#define JK_SO KC_C // ソ
#define JK_TA KC_Q // タ
#define JK_CHI KC_A // チ
#define JK_TSU KC_Z // ツ
#define JK_TE KC_W // テ
#define JK_TO KC_S // ト
#define JK_HA KC_F // ハ
#define JK_HI KC_V // ヒ
#define JK_FU KC_2 // フ
#define JK_HE KC_EQUAL // ヘ
#define JK_HO KC_MINUS // ホ
#define JK_YA KC_7 // ヤ
#define JK_YU KC_8 // ユ
#define JK_YO KC_9 // ヨ
#define JK_A KC_3 // ア
#define JK_I KC_E // イ
#define JK_U KC_4 // ウ
#define JK_E KC_5 // エ
#define JK_O KC_6 // オ
#define JK_RA KC_O // ラ
#define JK_RI KC_L // リ
#define JK_RU KC_DOT // ル
#define JK_RE KC_SCLN // レ
#define JK_RO KC_GRV // ロ
#define JK_MA KC_J // マ
#define JK_MI KC_N // ミ
#define JK_MU KC_BSLS // ム
#define JK_ME KC_SLSH // メ
#define JK_MO KC_M // モ
#define JK_NA KC_U // ナ
#define JK_NI KC_I // ニ
#define JK_NU KC_1 // ヌ
#define JK_NE KC_COMMA // ネ
#define JK_NO KC_K // ノ
#define JK_WA KC_0 // ワ
#define JK_WO KC_RPRN // ヲ
#define JK_N KC_Y // ン
#define JK_SEN KC_UNDS // ー
#define JK_DOT KC_GT // 。
#define JK_COM KC_LT // 、
#define JK_LQU KC_RCBR // 「
#define JK_RQU KC_PIPE // 」
#define JK_SLS KC_QUES // ・
#define JK_TEN KC_LBRC // ゛
#define JK_MAR KC_RBRC  // ゜


