#define JP_KA KC_T // カ
#define JP_KI KC_G // キ
#define JP_KU KC_H // ク
#define JP_KE KC_QUOT // ケ
#define JP_KO KC_B // コ
#define JP_SA KC_X // サ
#define JP_SHI KC_D // シ
#define JP_SU KC_R // ス
#define JP_SE KC_P // セ
#define JP_SO KC_C // ソ
#define JP_TA KC_Q // タ
#define JP_CHI KC_A // チ
#define JP_TSU KC_Z // ツ
#define JP_TE KC_W // テ
#define JP_TO KC_S // ト
#define JP_HA KC_F // ハ
#define JP_HI KC_V // ヒ
#define JP_FU KC_2 // フ
#define JP_HE KC_EQUAL // ヘ
#define JP_HO KC_MIN // ホ
#define JP_YA KC_7 // ヤ
#define JP_YU KC_8 // ユ
#define JP_YO KC_9 // ヨ
#define JP_A KC_3 // ア
#define JP_I KC_E // イ
#define JP_U KC_4 // ウ
#define JP_E KC_5 // エ
#define JP_O KC_6 // オ
#define JP_RA KC_O // ラ
#define JP_RI KC_L // リ
#define JP_RU KC_DOT // ル
#define JP_RE KC_SCLN // レ
#define JP_RO KC_GRV // ロ
#define JP_MA KC_J // マ
#define JP_MI KC_N // ミ
#define JP_MU KC_BSLS // ム
#define JP_ME KC_SLSH // メ
#define JP_MO KC_M // モ
#define JP_NA KC_U // ナ
#define JP_NI KC_I // ニ
#define JP_NU KC_1 // ヌ
#define JP_NE KC_COMMA // ネ
#define JP_NO KC_K // ノ
#define JP_WA KC_0 // ワ
#define JP_WO KC_RPRN // ヲ
#define JP_N KC_Y // ン
#define JP_SEN KC_UNDS // ー
#define JP_DOT KC_GT // 。
#define JP_COM KC_LT // 、
#define JP_LQU KC_RCBR // 「
#define JP_RQU KC_PIPE // 」
#define JP_SLS KC_QUES // ・
#define JP_TEN KC_LBRC // ゛
#define JP_MAR KC_RBRC  // ゜


